from django.urls import path
from JobApp import views

urlpatterns = [
    path('',views.Jobview.as_view(),name='home'),
    
    path('bank_job', views.jobcategory, name='bank_job'),
    path('bank_job/<slug:data>', views.jobcategory, name='bank_jobs'),
    path('bank_job/<slug:data>', views.jobcategory, name='Upsc_jobs'),
    path('bank_job/<slug:data>', views.jobcategory, name='ssc_jobs'),
    path('bank_job/<slug:data>', views.jobcategory, name='defence/police_jobs'),
    path('bank_job/<slug:data>', views.jobcategory, name='Railways_jobs'),
    path('bank_job/<slug:data>', views.jobcategory, name='medical_jobs'),
    path('bank_job/<slug:data>', views.jobcategory, name='Teaching_jobs'),
    path('bank_job/<slug:data>', views.jobcategory, name='Engineering_jobs'),

    path('state_job/<slug:data>', views.statejob, name='Andaman_Nicobar_Islands'),
    path('state_job/<slug:data>', views.statejob, name='Andhra_Pradesh'),
    path('state_job/<slug:data>', views.statejob, name='Arunachal_Pradesh'),
    path('state_job/<slug:data>', views.statejob, name='Assam'),
    path('state_job/<slug:data>', views.statejob, name='Bihar'),
    path('state_job/<slug:data>', views.statejob, name='Chandigarh'),
    path('state_job/<slug:data>', views.statejob, name='Dadra_Nagar_Haveli'),
    path('state_job/<slug:data>', views.statejob, name='Daman_and_Diu'),
    path('state_job/<slug:data>', views.statejob, name='Delhi'),
    path('state_job/<slug:data>', views.statejob, name='Goa'),
    path('state_job/<slug:data>', views.statejob, name='Gujarat'),
    path('state_job/<slug:data>', views.statejob, name='Haryana'),
    path('state_job/<slug:data>', views.statejob, name='Himachal_Pradesh'),
    path('state_job/<slug:data>', views.statejob, name='Jammu_Kashmir'),
    path('state_job/<slug:data>', views.statejob, name='Jharkhand'),
    path('state_job/<slug:data>', views.statejob, name='Karnataka'),
    path('state_job/<slug:data>', views.statejob, name='Kerala'),
    path('state_job/<slug:data>', views.statejob, name='Lakshadweep'),
    path('state_job/<slug:data>', views.statejob, name='Madhya Pradesh'),
    path('state_job/<slug:data>', views.statejob, name='Maharashtra'),
    path('state_job/<slug:data>', views.statejob, name='Manipur'),
    path('state_job/<slug:data>', views.statejob, name='Meghalaya'),
    path('state_job/<slug:data>', views.statejob, name='Mizoram'),
    path('state_job/<slug:data>', views.statejob, name='Nagaland'),
    path('state_job/<slug:data>', views.statejob, name='Odisha'),
    path('state_job/<slug:data>', views.statejob, name='Puducherry'),
    path('state_job/<slug:data>', views.statejob, name='Punjab'),
    path('state_job/<slug:data>', views.statejob, name='Rajasthan'),
    path('state_job/<slug:data>', views.statejob, name='Sikkim'),
    path('state_job/<slug:data>', views.statejob, name='Tamil_Nadu'),
    path('state_job/<slug:data>', views.statejob, name='Telangana'),
    path('state_job/<slug:data>', views.statejob, name='Tripura'),
    path('state_job/<slug:data>', views.statejob, name='Uttarakhand'),
    path('state_job/<slug:data>', views.statejob, name='Uttar_Pradesh'),
    path('state_job/<slug:data>', views.statejob, name='West_Bengal'),
    path('state_job/<slug:data>', views.statejob, name='All_India'),


    path('job_detail/<int:pk>', views.JobDetailView.as_view(), name='job_details'),
]
