# Generated by Django 4.0.4 on 2022-05-13 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=250)),
                ('start_date', models.DateField(blank=True)),
                ('last_date', models.DateField()),
                ('qulifications', models.CharField(max_length=250)),
                ('age_limit', models.CharField(max_length=250)),
                ('job_post', models.CharField(blank=True, max_length=250)),
                ('job_category', models.CharField(choices=[('B', 'Bank job'), ('U', 'Upsc job'), ('S', 'Ssc'), ('DF', 'Defence/Police Job'), ('DF', 'Railways Job'), ('DF', 'Medical Job'), ('DF', 'Teachimg Job'), ('DF', 'Engineering Job')], max_length=50)),
                ('state', models.CharField(choices=[('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chandigarh', 'Chandigarh'), ('Chhattisgarh', 'Chhattisgarh'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Daman and Diu', 'Daman and Diu'), ('Delhi', 'Delhi'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Lakshadweep', 'Lakshadweep'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Puducherry', 'Puducherry'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttarakhand', 'Uttarakhand'), ('Uttar Pradesh', 'Uttar Pradesh'), ('West Bengal', 'West Bengal'), ('All', 'All India')], max_length=50)),
                ('job_borad', models.CharField(blank=True, max_length=250)),
                ('job_description', models.TextField()),
                ('notification_no', models.CharField(blank=True, max_length=250)),
                ('notice', models.FileField(upload_to='media/notice')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_verify', models.BooleanField(default=False)),
                ('is_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
