# Generated by Django 4.0.4 on 2022-05-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobApp', '0004_jobpost_notice_link_alter_jobpost_age_limit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='qulifications',
            new_name='qualifications',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='recruitment_post',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_post',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
