# Generated by Django 4.0.4 on 2022-05-21 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobApp', '0005_rename_qulifications_jobpost_qualifications_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobNatificationsMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Noticebord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice', models.CharField(blank=True, max_length=250)),
                ('description', models.TextField(blank=True)),
                ('link', models.URLField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='last_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='notice_link',
            field=models.URLField(blank=True),
        ),
    ]
