# Generated by Django 4.0.4 on 2022-05-27 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobApp', '0007_jobpost_apply_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticebord',
            name='is_verify',
            field=models.BooleanField(default=False),
        ),
    ]
